epm_django/urls.py
from django.conf.urls import url, include
from epmcollect.admin import admin_site

urlpatterns = [
    url(r'^epmcontrol/', admin_site.urls),
    url(r'^epmcollect/', include('epmcollect.urls'))
]

epmcollect/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'epmcollect'

urlpatterns = [
    # /epmcollect/
    url(r'^$', views.index, name='index'),

    # /epmcollect/thanks - for generic thanking
    url(r'^thanks/$', views.thanks, name='thanks'),

    # /epmcollect/projects
    url(r'^projects/$', views.ProjectListView.as_view(), name='projects'),
    # /epmcollect/projects/24
    url(r'^projects/(?P<pk>[0-9]+)/$', views.ProjectDetailView.as_view(), name='single_project'),

    # /epmcollect/bicc_returns/
    url(r'^bicc_returns/$', views.BICCReturnList.as_view(template_name='epmcollect/bicc_returns.html')),
    # /epmcollect/bicc_returns/10
    url(r'^bicc_returns/(?P<pk>[0-9]+)/$',
        views.BICCReturnDetailView.as_view(template_name='epmcollect/bicc_return.html'), name='bicc_return'),
    # /epm/collect/bicc_returns/preview/project/20
    url(r'^bicc_returns/preview/project/(?P<project_id>[0-9]+)/$', views.bicc_pre_submit_summary,
        name='bicc_pre_submit_summary'),
    # /epmcollect/bicc_returns/add
    url(r'^bicc_returns/new/$', views.bicc_new, name='bicc_new'),

    #/epmcollect/dca/23
    url(r'dca/(?P<pk>[0-9]+)/$', views.DeliveryConfidenceAssessmentView.as_view(), name='dca'),
    # # /epmcollect/dca/add
    # url(r'dca/add/$', views.DeliveryConfidenceAssessmentCreate.as_view(), name='dca-add'),
    # /epmcollect/dca/add
    url(r'^dca/add/project/(?P<project_id>[0-9]+)/$', views.dca_add, name='dca-add'),

    url(r'^graphic/stacked_column/1$', views.aggregate_returns_rag_per_quarter, name='aggregrate_graph'),
    url(r'^graphic/stacked_column/2/(?P<yearref>[0-9]+)/(?P<qref>[0-9]+)$', views.delivery_confidence_against_project_maturity, name='dca_project_maturity'),
    url(r'^login/$', auth_views.login, name='login')
]

epmcollect/models.py
# -*- coding: utf-8 -*-
"""
    epm.models
    ~~~~~~~~~~

    DESCRIPTION

    :copyright: (c) 2016 by MATTHEW LEMON.
    :license: MIT, see LICENSE for more details.
"""
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import models

from .utils import number_of_rags, ready_graph_context_for_json, rag_labels, gen_dft_id


# Create your models here.


class OrganisationType(models.Model):
    """
    Organisations in this system can be of various types.
    """
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Organisaton Types'

    def __str__(self):
        return "{}".format(self.name)


class Organisation(models.Model):
    """
    Standard organisation e.g. DfT, Highways Agency
    """
    organisation_type = models.ForeignKey(OrganisationType)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(self.name)

class OrganisationLocation(models.Model):
    """
    Organisations can have various locations (offices) so we need separation.
    """
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50, null=True, blank=True)
    address3 = models.CharField(max_length=50, null=True, blank=True)
    address4 = models.CharField(max_length=50, null=True, blank=True)
    address5 = models.CharField(max_length=50, null=True, blank=True)
    postcode = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Organisation Locations'

    def __str__(self):
        return "Address at for {}".format(self.address1)

class OrganisationGroup(models.Model):
    """
    Like a DfT Group. Not all will have them so they are only linked to team
    as an option. An OrganisationTeam links straight to an Organisation
    """
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Organisation Groups'

    def __str__(self):
        return "{} - {}".format(self.name, self.organisation)

class OrganisationDivision(models.Model):
    """
    Like Governance Division.
    """
    organisation_group = models.ForeignKey(OrganisationGroup, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Organisation Divisions'

    def __str__(self):
        return "{}".format(self.name)


class OrganisationTeamType(models.Model):
    """
    Type of a team. Project, Programme, Admin, etc
    """
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Organisation Team Types'

    def __str__(self):
        return "{}".format(self.name)


class OrganisationTeam(models.Model):
    """
    A team in an organisation, like Portfolio Team.
    """
    organisation_division = models.ForeignKey(OrganisationDivision, on_delete=models.CASCADE)
    organisation_team_type = models.ForeignKey(OrganisationTeamType, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Organisation Teams'

    def __str__(self):
        return "{}".format(self.name)


class ProjectStage(models.Model):
    """
    EPM ProjectStage class - used in the Milestones and Assurance return.
    """
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, null=True, blank=True, default='')

    class Meta:
        verbose_name = 'Project Stage'

    def abbreviate(self):
        """
        For some ProjectStage reprs, we need to return an abbreviation
        rather than the full string.
        :return:
        """
        try:
            s_list = self.name.split(' ')
            if len(s_list) > 1:
                abbrev = ''.join([x[0] for x in s_list])
                return abbrev
            else:
                return self.name
        except:
            return self.name

    def get_rag_count(self, quarter=None):
        """We need to get the count of RAGs for each ProjectStage, by Quarter optionally."""

        # this is how to do a nested list comp properly in Python
        # the big loop goes first, then the inner loop after
        if quarter:
            bicc_returns = [
                dca.biccreturn_set.first()
                for p in self.project_set.all()  # BIG loop
                for dca in p.epmcollect_deliveryconfidenceassessment_related.all() if
                dca.granted is True and dca.quarter == quarter  # inner loop
                ]
        else:
            bicc_returns = [
                dca.biccreturn_set.first()
                for p in self.project_set.all()  # BIG loop
                for dca in p.epmcollect_deliveryconfidenceassessment_related.all() if dca.granted == True
                ]

        rags = [r.sro_delivery_confidence_rag.rag.rag for r in bicc_returns]
        from collections import Counter
        count_rags = Counter(rags)
        labels = rag_labels()
        label = {'label': self.abbreviate()}
        context = {}
        context.update(count_rags)
        context.update(labels)
        context.update(label)
        return context

    def __repr__(self):
        return self.name

    def __str__(self):
        return "{}".format(self.name)


class ProjectMethodology(models.Model):
    """
    EPM ProjectMethodology class, for including definitions of 'waterfall', 'agile', etc.
    """
    methodology = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Project Methodologies"

    def __str__(self):
        return "{}".format(self.methodology)


class ConfidenceAssessmentBase(models.Model):
    """
    EPM ConfidenceAssessment base class, to be subclassed by other assessment classes.
    As an abstract class, this does not get a database table and it cannot be instantiated.
    """
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name="%(app_label)s_%(class)s_related")
    quarter = models.ForeignKey('Quarter', on_delete=models.CASCADE, related_name="%(app_label)s_%(class)s_related")
    date_assessed = models.DateField()
    assessor = models.ForeignKey('Person', on_delete=models.CASCADE, related_name="%(app_label)s_%(class)s_related")
    granted = models.BooleanField(default=False)  # in honour of Will Grant

    class Meta:
        abstract = True


class DeliveryConfidenceAssessment(ConfidenceAssessmentBase):
    """
    EPM DeliveryConfidenceAssessment class.
    """
    rag = models.ForeignKey('RAG')
    overall_commentary = models.TextField(max_length=2000)

    class Meta:
        verbose_name_plural = "Delivery Confidence Assessments"

    def get_absolute_url(self):
        return reverse('epmcollect:dca', kwargs={'pk': self.pk})

    def __str__(self):
        return "DC for {} for {}".format(self.project, self.quarter)


# TODO implement FinanceConfidenceAssessment and BenefitsConfidenceAssessment classes here


class Portfolio(models.Model):
    """
    EPM Portfolio model
    """
    name = models.CharField(max_length=30)

    @property
    def greens(self):
        return number_of_rags(self.name, "GREEN")

    @property
    def amber_greens(self):
        return number_of_rags(self.name, "AMBER/GREEN")

    @property
    def ambers(self):
        return number_of_rags(self.name, "AMBER")

    @property
    def amber_reds(self):
        return number_of_rags(self.name, "AMBER/RED")

    @property
    def reds(self):
        return number_of_rags(self.name, "RED")

    def __str__(self):
        return self.name


class Role(models.Model):
    """
    EPM Role model
    """
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class PLPStatus(models.Model):
    """
    Services SRODetails model.
    """
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    why_not_mpla = models.CharField(max_length=1000, verbose_name='Why not MPLA?')

    def __str__(self):
        return self.name


class MPLAStatus(models.Model):
    """
    Self-explanatory. Services the SRODetails model.
    """
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    why_not_plp = models.CharField(max_length=1000, verbose_name='Why not PLP?')

    def __str__(self):
        return self.name


class SRODetails(models.Model):
    """
    Additional details for the Person if they are an SRO.
    """
    sro_person = models.ForeignKey('Person', on_delete=models.CASCADE, verbose_name='SRO')
    pass
    sro_tenure_start = models.DateField(null=True, verbose_name='SRO Tenure Start')
    sro_letter_issued = models.BooleanField(default=True, verbose_name='SRO Letter Issued')
    sro_letter_issued_date = models.DateField(null=True, verbose_name='SRO Letter Issued Date')
    sro_tenure_end = models.DateField(null=True, verbose_name='SRO Tenure End', blank=True)
    percentage_time_in_role = models.IntegerField(default=100, verbose_name='Percentage time in SRO role', blank=True)
    additional_information_about_role = models.CharField(max_length=1000, default='', null=True, blank=True)
    mpla_status = models.ForeignKey(MPLAStatus, null=True, verbose_name='MPLA status', blank=True)
    plp_status = models.ForeignKey(PLPStatus, null=True, verbose_name='PLP status', blank=True)

    class Meta:
        verbose_name = 'SRO Details'
        verbose_name_plural = 'SRO Details'

    def __str__(self):
        try:

epmcollect/forms.py
from django import forms
from epmcollect.models import DeliveryConfidenceAssessment

class NewDCAForm(forms.ModelForm):
    class Meta:
        model = DeliveryConfidenceAssessment
        fields = ['quarter', 'date_assessed', 'assessor', 'rag', 'overall_commentary']

epmcollect/views.py
import json

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from epmcollect.forms import NewDCAForm
from epmcollect.graphics.stacked_column import DCAProjectMaturity, AggPortfolioDCA
from .models import Project, Quarter, DeliveryConfidenceAssessment, BICCReturn


# Create your views here.

# ------CLASS_BASED_VIEWS------------#

class ProjectListView(ListView):
    template_name = 'epmcollect/projects.html'
    model = Project
    context_object_name = 'all_projects'

    def get_queryset(self):
        return Project.objects.all()


class ProjectDetailView(DetailView):
    template_name = 'epmcollect/single_project.html'
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        project = kwargs['object']
        context['delivery_confidence_assessments'] = project.epmcollect_deliveryconfidenceassessment_related.all()
        context['project_data'] = project
        return context


class DeliveryConfidenceAssessmentView(DetailView):
    template_name = 'epmcollect/dca.html'
    context_object_name = 'dca_data'
    model = DeliveryConfidenceAssessment


class DeliveryConfidenceAssessmentCreate(CreateView):
    model = DeliveryConfidenceAssessment
    template_name = 'epmcollect/forms/dca-new.html'
    fields = ['project', 'quarter', 'rag', 'assessor', 'date_assessed', 'overall_commentary']


class BICCReturnList(ListView):
    model = BICCReturn
    context_object_name = 'bicc_returns'


class BICCReturnDetailView(DetailView):
    model = BICCReturn

    def get_context_data(self, **kwargs):
        context = super(BICCReturnDetailView, self).get_context_data(**kwargs)
        bicc_return = kwargs['object']
        context['bicc_return'] = bicc_return
        return context


# ------FUNCTION-BASED_VIEWS---------#

def index(request):
    user = request.user.username
    owned_projects = Project.objects.filter(owner__username=user)
    context = {
        'user': user,
        'owned_projects': owned_projects
    }
    return render(request, 'epmcollect/index.html', context)


def login(request):
    return render(request, 'registration/login.html')


def aggregate_returns_rag_per_quarter(request):
    graph_object = AggPortfolioDCA()
    data = graph_object.generate_graph_data()
    data_dict = json.dumps(data)

    context = {
        'view_json': data_dict
    }
    return render(request, 'epmcollect/single_graph.html', context)


def delivery_confidence_against_project_maturity(request, yearref, qref):
    q = Quarter.objects.get(yearref=yearref, qref=qref)
    graph_object = DCAProjectMaturity(q)
    data = graph_object.generate_graph_data()
    json_data = json.dumps(data)
    context = {
        'view_json': json_data,
        'quarter_label': q.get_label()
    }
    return render(request, 'epmcollect/single_graph_dca_maturity.html', context)


def dca_add(request, project_id):
    if request.method == 'POST':
        form = NewDCAForm(request.POST)
        if form.is_valid():
            quarter = form.cleaned_data['quarter']
            date_assessed = form.cleaned_data['date_assessed']
            assessor = form.cleaned_data['assessor']
            rag = form.cleaned_data['rag']
            overall_commentary = form.cleaned_data['overall_commentary']

            # process the request:
            dca = DeliveryConfidenceAssessment(
                project_id=project_id,
                quarter=quarter,
                date_assessed=date_assessed,
                assessor=assessor,
                rag=rag,
                overall_commentary=overall_commentary
            )
            dca.save()

            return HttpResponseRedirect('/epmcollect/thanks/')
    else:
        form = NewDCAForm()
        project = Project.objects.get(id=project_id).name
    return render(request, 'epmcollect/forms/dca-new.html', {'form': form, 'project': project})


def thanks(request):
    return render(request, 'epmcollect/thanks.html')


def bicc_pre_submit_summary(request, project_id):
    project = Project.objects.get(id=project_id)
    ungranted_assessments = [dca for dca in project.epmcollect_deliveryconfidenceassessment_related.all()
                             if dca.granted == False]
    context = {
        'project': project,
        'ungranted_assessments': ungranted_assessments
    }
    return render(request, 'epmcollect/bicc_preview.html', context)


def bicc_new(request):
    if request.method == 'POST':
        dca_id = request.POST.get('dca_id')
        # first we grant the dca
        dca = DeliveryConfidenceAssessment.objects.get(id=dca_id)
        dca.granted = True
        dca.save()
        # now we create and save the BICC return with this razzer in it
        bicc_return = BICCReturn(sro_delivery_confidence_rag=dca)
        bicc_return.save()
        return render(request, 'epmcollect/bicc_new_confirm.html', {'bicc_return': bicc_return})

epmcollect/templates/epmcollect/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Evolved Portfolio Management (EPM){% endblock %}</title>
</head>
<body>
<div id="top-navigation" style="background-color: azure">
   <h3>navbar</h3>
</div>
    {% block content %}

    {% endblock %}

</body>
</html>

epmcollect/templates/epmcollect/bicc_new_confirm.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}
<h2>BICC Return Submitted - Thank you!</h2>

{{ bicc_return.sro_delivery_confidence_rag.id }}
{% endblock %}

epmcollect/templates/epmcollect/bicc_preview.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

    <h3>Components to submit as BICC return</h3>

    <h4>{{ project }}</h4>


    <table>
        <tr>
            <th>Assessment</th>
            <th>Summary</th>
            <th>Commentary</th>
            <th>Action</th>
        </tr>
        {% for component in ungranted_assessments %}
            <tr>
                <td>{{ component.id }}</td>
                <td>{{ component.rag }}</td>
                <td>{{ component.overall_commentary }}</td>
                <td><a href="#">edit</a></td>
            </tr>
            {% if ungranted_assessments %}
                <form action="/epmcollect/bicc_returns/new/" method="post">
                    {% csrf_token %}
                    <input type="hidden" id="project_id" name="project_id" value="{{ project.id }}">
                    <input type="hidden" id="dca_id" name="dca_id" value="{{ component.id }}">
                    <input type="hidden" id="TEST" name="TEST" value="TEST">
                    <input type="submit" value="Submit BICC Return">
                </form>
            {% else %}
                <p>There are no unsubmitted assessments</p>
            {% endif %}
        {% endfor %}
    </table>




{% endblock %}

epmcollect/templates/epmcollect/bicc_return.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

    <h1>BICC Return Data</h1>

    <h2>{{ bicc_return.sro_delivery_confidence_rag.project }}</h2>

    <h3>{{ bicc_return.sro_delivery_confidence_rag.quarter }}</h3>

    <h4>Delivery Confidence Assessment</h4>

    <p>{{ bicc_return.sro_delivery_confidence_rag.rag }}</p>

{% endblock %}

epmcollect/templates/epmcollect/bicc_returns.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

    <h1>BICC Returns</h1>

    <table>
    <tr>
       <th>Delivery Confidence Assessments</th>
    </tr>
    {% for bicc_return in bicc_returns %}
        <tr>
        <td>{{ bicc_return.sro_delivery_confidence_rag.date_assessed }}: <a href="{% url 'epmcollect:bicc_return' bicc_return.id %}">{{ bicc_return.sro_delivery_confidence_rag }}</a></td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

epmcollect/templates/epmcollect/dca.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

<h1>Details for DCA</h1>

    <p>{{ dca_data.rag }}</p>

{% endblock %}

epmcollect/templates/epmcollect/index.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

    <h1>Welcome to EPM!</h1>

    <p>Welcome {{ user }}</p>

    <div id="project-list">
    <h3>Projects owned by {{ user }}</h3>
        <table id="project-list-table">
            <tr>
                <th>Project</th>
            </tr>
            {% for project in owned_projects %}
                <tr>
                    <td><a href="{% url 'epmcollect:single_project' project.id %}">{{ project.name }}</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

epmcollect/templates/epmcollect/new_return.html
<h1>Submit a BICC return</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url  %}"></form>

epmcollect/templates/epmcollect/projects.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

<h1>Projects</h1>

<table>
    <tr>
        <th>Project Name</th>
        <th>Project SRO</th>
        <th>Project RAG Rating</th>
    </tr>
    {% for project in all_projects %}
    <tr>
        <td>{{ project.name }}</td>
        <td>{{ project.sro }}</td>
        <td>{{ project.sro_rating }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

epmcollect/templates/epmcollect/single_graph.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script type="text/javascript" src="/static/epmcollect/epmcharts.js"></script>

<div style="width: 400px;"><h1>Single Graph Test Page</h1></div>

    <p>{{ view_json }}</p>

<script type="text/javascript">
    var viewJSON = {{ view_json|safe }};
</script>

<script type="text/javascript">
    $(document).ready(columnSort);
</script>


<script type="text/javascript">
    $(document).ready(aggregateRAGChartMulti);
</script>
<div id="agg_rag_multi" style="min-width: 310px; max-width: 600px; height: 500px; margin: 0 auto"></div>

{% endblock %}

epmcollect/templates/epmcollect/single_graph_dca_maturity.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script type="text/javascript" src="/static/epmcollect/epmcharts.js"></script>

<div style="width: 400px;"><h1>Single Graph Test Page</h1></div>

    <p>{{ view_json }}</p>
    <p>{{ quarter_label }}</p>

<script type="text/javascript">
    var viewJSON = {{ view_json|safe }};
    var quarterLabel = '{{ quarter_label|safe }}'
</script>


<script type="text/javascript">
    $(document).ready(DCAChart);
</script>
<div id="agg_rag_multi" style="min-width: 310px; max-width: 600px; height: 500px; margin: 0 auto"></div>

{% endblock %}

epmcollect/templates/epmcollect/single_project.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}

    <h1>{{ project_data.name }}</h1>

    <div style="float: left; background-color: lavender; border: double black; clear: both; padding: 10px; width: 800px;">
        <table id="project-details-table">
            <tr>
                <th>Project name</th>
                <th>Portfolio</th>
                <th>SRO</th>
                <th>Current SRO rating</th>
            </tr>
            <tr>
                <td>{{ project_data.name }}</td>
                <td>
                    {% for portfolio in project_data.portfolios.all %}
                        {{ portfolio.name }}
                    {% endfor %}
                </td>
                <td>{{ project_data.sro }}</td>
                <td>{{ project_data.sro_rating }}</td>
            </tr>
        </table>
    </div>



    <div style="float: left; background-color: azure; border: double black; clear: both; padding: 10px; width: 800px">
        <h3>Next BICC return</h3>
        <table style="border: 1px solid black; width: 100%;">
            <tr>
                <td><strong>Quarter:</strong></td>
                <td>Q1/2016</td>
                <td></td>
            </tr>
            <tr>
                <td><strong>Due:</strong></td>
                <td>27-07-16</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td><strong>Status:</strong></td>
                <td style="color: red;">INCOMPLETE</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td><strong>Portfolio submissions:</strong></td>
                <td>28 of 40 projects have submitted</td>
                <td>
                    <a href="{% url 'epmcollect:bicc_pre_submit_summary' project_data.id %}">Submit BICC Return</a>
                </td>
            </tr>
        </table>
    </div>

    <div style="background-color: azure; border: double black; clear: both; float: left; padding: 10px; width: 800px;">
        <h4>BICC Return Component Status</h4>
        <table style="border: 1px solid black; width: 100%;">
            <tr>
                <th>Component</th>
                <th>Status</th>
                <th>Edit link</th>
            </tr>
            <tr>
                <td>Delivery Capability Assessment</td>
                <td style="color: green;">VERIFIED</td>
                <td><a href="{% url 'epmcollect:dca-add' project_data.id %}">link to DCA form</a></td>
            </tr>
            <tr>
                <td>Finance Capability Assessment</td>
                <td style="color: red;">INCOMPLETE</td>
                <td><a href="#">link to FCA form</a></td>
            </tr>
            <tr>
                <td>Benefits Capability Assessment</td>
                <td style="color: red;">INCOMPLETE</td>
                <td><a href="#">link to BCA form</a></td>
            </tr>
        </table>
    </div>

    <div style="float: left; background-color: azure; border: double black; clear: both; padding: 10px; width: 800px; ">
        <h3>Previous BICC Returns for this Project</h3>
        <table style="border: 1px solid black; width: 100%;">
            <tr>
                <th>Quarter</th>
                <th>Date Submitted</th>
                <th>Summary</th>
            </tr>
            <tr>
                <td>Q4/2015</td>
                <td>20-06-16</td>
                <td><a href="#">link to BICC Return summary</a></td>
            </tr>
            <tr>
                <td>Q3/2015</td>
                <td>20-03-16</td>
                <td><a href="#">link to BICC Return summary</a></td>
            </tr>
            <tr>
                <td>...etc</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
    </div>

{% endblock %}

epmcollect/templates/epmcollect/thanks.html
{% extends 'epmcollect/base_generic.html' %}

{% block content %}
<h1>Thanks!</h1>

<p>Thanks for submitting your form, or whatever you did.</p>

<p><a href="{% url 'epmcollect:index' %}">Back home</a></p>
{% endblock %}